# yamllint disable rule:line-length
# yamllint disable rule:braces

name: CI

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  phpunit:
    name: "PHPUnit"
    runs-on: "ubuntu-20.04"

    strategy:
      fail-fast: false
      matrix:
        symfony-version:
          - '^4.4'
          - '^5.4'
          - '^6.4'
        php-version:
          - "8.0"
          - "8.1"
        dependencies:
          - "lowest"
          - "highest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "pcov"
          ini-values: "zend.assertions=1"

      - name: Configure symfony version
        uses: php-actions/composer@v6
        with:
          command: config
          args: extra.symfony.require ${{ matrix.symfony-version }}

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v1"
        with:
          dependency-versions: "${{ matrix.dependencies }}"
          composer-options: "${{ matrix.composer-options }}"

      - name: Run tests
        run: |
          SYMFONY_DEPRECATIONS_HELPER=weak vendor/bin/simple-phpunit ${PHPUNIT_FLAGS}
